### ISSUE TITLE
missed ad in AngryBirds (android 6)

### ISSUE THREAD

**Issue by Michael23456** [AdguardTeam/AdguardFilters#5060]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: missed ad in AngryBirds (android 6)
https://play.google.com/store/apps/details?id=com.rovio.angrybirdsstarwarshd.premium.iap

Screenshot: 
![image](https://cloud.githubusercontent.com/assets/25711093/26284269/dd8aca16-3e3f-11e7-9d82-0e5a35d84900.png)

***System configuration***

Information | value
--- | ---
Operating system: | Android 6
Adguard version: | 2.9.70
Adguard mode (Android): | VPN 
Filtering quality (Android): | High-quality 
HTTPS filtering (Android): |  On 
Adguard filters: | end, rus, mobile, annoyance, social, spyware

time in logs = 8.27
[debug (95).txt](https://github.com/AdguardTeam/AdguardFilters/files/1017008/debug.95.txt)

Ticket ID(if exists): 1208748

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Can't reproduce. When it happens?

**Comment by Michael23456** [comment]
waiting for an answer from the customer

**Comment by Michael23456** [comment]
пришел ответ "Появляется после прохождения каждого уровня"

**Comment by Alex-302** [comment]
Похоже фильтрация https не работает для cloud.rovio.com
```
21:31:44.026 [pool-3-thread-240] INFO  com.adguard.filter.proxy.ssl.l - TCP id=1000912 Adding endpoint com.rovio.angrybirdsstarwarshd.premium.iap_54.89.64.115_443_cloud.rovio.com to exceptions due to class java.io.IOException: Internal TLS error, this could be an attack
21:31:44.026 [pool-3-thread-232] INFO  com.adguard.filter.proxy.ssl.l - TCP id=1000913 Adding endpoint com.rovio.angrybirdsstarwarshd.premium.iap_54.89.64.115_443_cloud.rovio.com to exceptions due to class java.io.IOException: Internal TLS error, this could be an attack
21:31:44.028 [pool-3-thread-232] ERROR com.adguard.filter.proxy.a - TCP id=1000913 Error while processing connection. Connection info: com.rovio.angrybirdsstarwarshd.premium.iap /172.16.209.1:58628 /54.89.64.115:443 10584

java.io.IOException: Internal TLS error, this could be an attack
	at org.bouncycastle.crypto.tls.TlsProtocol.processAlert(Unknown Source) ~[na:0.0]
	at org.bouncycastle.crypto.tls.TlsProtocol.processRecord(Unknown Source) ~[na:0.0]
	at org.bouncycastle.crypto.tls.RecordStream.readRecord(Unknown Source) ~[na:0.0]
	at org.bouncycastle.crypto.tls.TlsProtocol.safeReadRecord(Unknown Source) ~[na:0.0]
	at org.bouncycastle.crypto.tls.TlsProtocol.completeHandshake(Unknown Source) ~[na:0.0]
	at org.bouncycastle.crypto.tls.TlsServerProtocol.accept(Unknown Source) ~[na:0.0]
	at com.adguard.filter.proxy.ssl.l.a(Unknown Source) ~[na:0.0]
	at com.adguard.filter.proxy.ssl.l.a(Unknown Source) ~[na:0.0]
	at com.adguard.filter.proxy.a.a(Unknown Source) ~[na:0.0]
	at com.adguard.android.filtering.filter.i.a(Unknown Source) ~[na:0.0]
	at com.adguard.filter.proxy.a.a(Unknown Source) ~[na:0.0]
	at com.adguard.android.filtering.filter.i.a(Unknown Source) ~[na:0.0]
	at com.adguard.filter.proxy.n.a(Unknown Source) ~[na:0.0]
	at com.adguard.filter.proxy.n$2.run(Unknown Source) ~[na:0.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) ~[na:0.0]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) ~[na:0.0]
	at java.lang.Thread.run(Thread.java:818) ~[na:0.0]
```

**Comment by Michael23456** [comment]
а что ответить?

**Comment by Alex-302** [comment]
пока не знаю

**Comment by ameshkov** [comment]
@Alex-302 ну это не баг, такое иногда случается с некоторыми приложениями. Значит не получится хттпс отфильтровать для этого домена
